### ISSUE TITLE
Too many trainers and explorers can be bought

### ISSUE THREAD

**Issue by spindrjr** [zininzinin/AutoTrimps#10]
Somehow the script is able to buy too many explorers and trainers. Does not always happen and not always to both.

Example current run: trainers OK at 578 owned, 20 mins ETA to upgrade. Explorers broken at 907 owned, 33.5 billion years ETA to upgrade. Have had trainers as high as 2200 before with absurd amount of years until upgrade. When this happens, current cost appears to be correct given cost growth rates from wiki.

**Comment by weltvagabund** [comment]
I can confirm this issue in build #6 
Recreate:
http://pastebin.com/TPnq2xuB
Activate Buy Jobs
11600 Trainer
Similar with explorers when you fire them before activate Jobs

**Comment by WG-SpaceCoder** [comment]
Should be fixed in latest master.

**Comment by weltvagabund** [comment]
I tested it and can confirm it works now.
One Thiong i Found: Normal Jobs are bought always, Trainers and Explorers only if you switch from Custom (1B) to 1. But I consider that just an inconvinience
