### ISSUE TITLE
autoMaps status stuck on "Prepping for Voids" with no void maps

### ISSUE THREAD

**Issue by coderpatsy** [zininzinin/AutoTrimps#100]
Steps to reproduce: Have no void maps, and set the zone for running void maps less than current zone.

Suggested fix: Don't display that status if you have no void maps to prep for.

You did say it was experimental, haha.

**Comment by spindrjr** [comment]
Hey thanks for the report. I actually already fixed this in my dev version which I'll probably push sometime later tonight.

**Comment by spindrjr** [comment]
Should be fixed. Thanks again.
