### ISSUE TITLE
str.includes plyfill

### ISSUE THREAD

**Issue by ghost** [zininzinin/AutoTrimps#102]
when running the script in palemoon 26.1.1 it gives the following error:

> TypeError: game.global.buildingsQueue[b].includes is not a function @ https://zininzinin.github.io/AutoTrimps/AutoTrimps2.js:203

this can be fixed by adding the following polyfill for it:

```
if (!String.prototype.includes) {
  String.prototype.includes = function(search, start) {
    'use strict';
    if (typeof start !== 'number') {
      start = 0;
    }

    if (start + search.length > this.length) {
      return false;
    } else {
      return this.indexOf(search, start) !== -1;
    }
  };
}
```

**Comment by spindrjr** [comment]
I don't know anything about this stuff but I think I got it in there for you. I'll close this and just let me know if it doesn't work (and probably also let me know what to do to fix it :P )
