### ISSUE TITLE
Auto Maps - Farming vs map damage stacks

### ISSUE THREAD

**Issue by coderpatsy** [zininzinin/AutoTrimps#104]
When Auto Maps is "Farming" it appears to go through the zone to get the books, even when the zone is difficult. Can this perhaps be changed so that it gets map stacks before running through the zone?

**Comment by spindrjr** [comment]
Thank you for the suggestion. Unfortunately I do not see an easy way to implement this. Coupled with the fact that the benefits are dampened by the reduced resources gained during the stacking, makes me not inclined to change this.

In my previous testing, I found that, although somewhat slow, the overall time to get to what I call the 'sitting' spot to farm is on par with the time it would take to get the 10 stacks. Also keep in mind that the coming patch will introduce increased level of critical hits and damage, which will help alleviate dps during these phases.

However, if you are experiencing what you think are unusual or unacceptable delays in reaching the sitting spot, please provide me a save export and a picture of your settings and I would be happy to take a look.

**Comment by coderpatsy** [comment]
Ah. Well that makes sense I guess.
