### ISSUE TITLE
heirloom metal drop

### ISSUE THREAD

**Issue by McCloude** [zininzinin/AutoTrimps#109]
Looking through how the heirloom section works.  

Line 593, you're checking for miner efficiency.  
`if(!checkForMod('MinerSpeed', index, location)){
                    eff += 0.75*av/100;
                    }`

Should metal drop also be valued here?
`if(!checkForMod('MinerSpeed', index, location) || !checkForMod('metalDrop', index, location)){
                    eff += 0.75*av/100;
                    }`

**Comment by spindrjr** [comment]
This should be fixed in the latest push. Thanks.
