### ISSUE TITLE
Prestige + Siphonology

### ISSUE THREAD

**Issue by Xallen79** [zininzinin/AutoTrimps#111]
Siphonology 3
Prestiging Megamace 

I hit level 152 about an hour ago.   Automaps says Prestige, but it keeps creating level 148 maps (I now have ~120 level 149 maps)

[trimps_prestige.txt](https://github.com/zininzinin/AutoTrimps/files/173885/trimps_prestige.txt)

Edit:
I should mention I don't have the version from 3/14. Trying that now.

Edit 2:
Still happens with the latest version.

**Comment by spindrjr** [comment]
Hey thanks for reporting this and especially for providing a save! I just pushed a version that should fix this.
