### ISSUE TITLE
Auto-hide portals behind X last in graphs

### ISSUE THREAD

**Issue by Anahkiasen** [zininzinin/AutoTrimps#116]
The graphs are amazing but after a certain number of ascensions they can get rather crowded. It would be a good addition if an option could be added to only show the last X runs – either that or make it remember which runs were hidden/shown when you open/close the graphs section.

Unless it does that already and I just haven't done enough runs for it to kick in, I'm at my 9th portal, in which case this can be closed :D

**Comment by spindrjr** [comment]
You're real close! It shows a maximum of 10 past runs, so 11 total series including the current run. I do have on my list to consider adding more options for clearing the data to the interface, but for now you can do it yourself using the command clearData(x) in the console (opened with f12 generally). This will clear data and keep only x previous portals, not including the current run. So for example the base code calls clearData(10) to keep the past 10 portals, and the current run.
