### ISSUE TITLE
Hide Fight and Autofight if AutoTrimp's autofight is enabled

### ISSUE THREAD

**Issue by Anahkiasen** [zininzinin/AutoTrimps#122]
I have what I consider to be a moderately big screen (27") but even on that all the buttons don't fit in the lower-right area. Since Autotrimps add a few ones plus the Automap status, I think maybe it would be better if the Fight and Autofight buttons were hidden when AT's autofight is enabled, since clicking them won't do anything anyway.

![screen shot 2016-03-22 at 22 47 08](https://cloud.githubusercontent.com/assets/1321596/13968946/0733ae50-f080-11e5-8543-62b00ec12d75.png)

**Comment by spindrjr** [comment]
Unfortunately I don't see a straightforward way to do this. Combined with the confusion it may cause, it probably won't happen. Is your aspect ratio something other than 16:9? Or are you running the window at some other ratio? I'm running 1440p and don't really come anywhere close to this happening. I wouldn't expect any 27" to be anything lower than 1080 and it doesn't seem like it should happen with that either (though admittedly I am too lazy to change my resolution and check). 

This can however be changed by shrinking the horizontal space used by the display, either by shrinking the window horizontally, or by having the console open on the right (which I do all the time to watch the log messages, but may not be your cup of tea).

**Comment by Anahkiasen** [comment]
What about reducing the font size of the buttons, and/or the padding? They rarely go off screen like they do on the screenshot, per example I see all the buttons at the moment, but I still rarely see the automap status. I mean screen size nonetheless, those buttons take up a lot of screen estate and often go out their box, I'm thinking maybe reducing their size would help

EDIT: I think what happened on the screenshot maybe is the map's name was too long and went on two lines, causing one button to go offscreen

**Comment by spindrjr** [comment]
Try it now. Should have hopefully shrunk the padding on the buttons.

**Comment by Anahkiasen** [comment]
My computer crashed so I had to restart from scratch which means no Heirlooms nor Portals buttons, but from what I can see it looks better indeed. Thanks!
