### ISSUE TITLE
Mass Warpstation on upgrade Gigastation

### ISSUE THREAD

**Issue by morawcik** [zininzinin/AutoTrimps#125]
It's possible to buy e.g. 100 warpstation in one stock on upgrade gigastation? On upgrade script buy (actual on my run) 500+ warpstation and I get freeze game for 10-20s

**Comment by spindrjr** [comment]
I just pushed a version that should do this. Not sure how much it will help performance since it still has to loop quite a bit to figure out how many it can afford, but let me know how it goes for you. Should hopefully be about half as many total function calls in a big purchase.

**Comment by morawcik** [comment]
Wow, now it's awesome! No freeze, no lags. Thank You very much :)
