### ISSUE TITLE
Problem with amount buttons in jobs

### ISSUE THREAD

**Issue by morawcik** [zininzinin/AutoTrimps#128]
Hi.
I have problem with amount buttons. E.g. if I click 25x then e.g click Miner I hire only 1 miner

**Comment by Anahkiasen** [comment]
I'm guessing it's just Autotrimps firing the extra miners to fit the ratio you configured no?

**Comment by morawcik** [comment]
Yep, it's because of auto job but why override amount buttons value?

**Comment by spindrjr** [comment]
Works fine for me. Do you have more than 1 available work space when you are trying to buy?

**Comment by morawcik** [comment]
Yes, for now stay at 2m

**Comment by spindrjr** [comment]
If you give me your save and a picture of your autoTrimp settings I can take a look. Code looks fine and it all works fine for me.

**Comment by morawcik** [comment]
So it's sth with my browser/pc. After pc restart everything back to normal. Sorry for "problem" :(
