### ISSUE TITLE
Automaps sometimes get stuck running unique maps

### ISSUE THREAD

**Issue by Anahkiasen** [zininzinin/AutoTrimps#129]
I've seen this happen a bunch of times, it seems that sometimes the Automaps generates a map for the current zone, when there's an unique map also available, and it gets stuck running the unique map instead of the generated one.

In all cases where I've seen this happen the unique map was always first before the generated map in the list so I'm not sure if maybe the Automaps is just picking the last map in the list?

![screen shot 2016-04-01 at 00 22 46](https://cloud.githubusercontent.com/assets/1321596/14192757/ff757f78-f79f-11e5-93bc-1cf6970a163f.png)

**Comment by spindrjr** [comment]
If you see it happen again please toss me an export and picture of your settings.

**Comment by spindrjr** [comment]
Were you at sort of low helium at the time for this? I noticed while doing underachiever that it will run the wall a lot as long as bounty is not bought yet (because you can't afford it). I changed this so that it will hopefully stop running wall as long as you have bounty available.

**Comment by Anahkiasen** [comment]
It's possible yes, I had to restart so I'm still at very early game (this happened at like 9th run). It's hard to find a save to export because if I disable the automaps, leave the unique map, and reenable it, it then correctly runs the generated map. Anyway, think you can close this, if I manage to catch it happening I'll try to do an export, see if it's of any value
