### ISSUE TITLE
Smart Buy Housing

### ISSUE THREAD

**Issue by WG-SpaceCoder** [zininzinin/AutoTrimps#13]
Buy housing based on gem efficiency for houses that require gems

**Comment by weltvagabund** [comment]
I support this, but I think it is less Important as soon as you break the Planet. Afterwards you tend to only buy the Housing in Batches up to a certain Limit and don't care about Gem Efficiency. Then suddenly Suggestion #15 is a lot more Important

**Comment by WG-SpaceCoder** [comment]
@weltvagabund I tend to agree, but I figure I'll do both. Look forward to both in v2.  

Initial version implemented in v2
