### ISSUE TITLE
[suggestion] new option for breed timer

### ISSUE THREAD

**Issue by morawcik** [zininzinin/AutoTrimps#130]
Hi.
It's possible to add new option that block manage breed timer or geneticist timer to max trimps/s ? What I mean? If I have 200B trimps that I want to breed time sth that 200B/s. Now I must manual disable manage breed timer and set geneticist timer to 0-1 and manualy buy geneticist.

**Comment by spindrjr** [comment]
Sorry I don't understand what you are asking for still. You want an option to block manage breed timer, how is that different than turning off manage breed timer?

**Comment by morawcik** [comment]
I want on manage breed timer but I want too that my breed time not dropped below max timps per sec - if I have 200B trimps that will be 200B/s

**Comment by spindrjr** [comment]
The main purpose of manage breed timer is to pick a breed timer for you. You apparently want to pick a breed timer of 1 second. What are you missing out on with having manage breed timer off to manually pick 1 second?

**Comment by morawcik** [comment]
If I set 1 second (for geneticist timer right?) that if I have full trimps that geneticists will be buy and I lost my breed time e.g from 1B/s to 1M/s

**Comment by spindrjr** [comment]
If you set it to 1 second, it should keep the time to breed a full army at 1 second at all times. It will have to adjust when you have large population cap increases, but it will stay at 1 second to breed an army. It will not hire geneticists to go over 1 second breed time, regardless of if your army is ready or not.

**Comment by morawcik** [comment]
Tested now (with geneticist timer set to 1) - If my trimps not die (and I have 0.0 Secs / 0.0 Secs on red bar) - below trimps count) breeed time dropped to 44M/s with 15B trimps. Which means if now my trimps die I need wait too long to fight without manualy fight (click fight button)

**Comment by spindrjr** [comment]
Abandon your soldiers to kill them. You will see they are back in < 1 sec.

**Comment by morawcik** [comment]
I "hack" for testing agility level to 1000 and my trimps die now 2-3 times per second and breed time now balance between 35-50M/s

**Comment by spindrjr** [comment]
You can't expect the game to behave correctly when you hack it and I'm certainly not going to implement options to fix behavior while hacked.

**Comment by morawcik** [comment]
I hack now only for tests and fast die. Ok maybe only fire geneticists if actual breed time is higer than geneticist breed timer option?

**Comment by spindrjr** [comment]
Firing them to speed up current breed time (first number) has a large impact on he/hr at higher levels. Firing them only speeds up breed time, though, which seems to be what you are after, so I'm still confused as to what you want.

**Comment by morawcik** [comment]
Oh, I see, the cost is too high for firing and hiring again and again. So I must be more patient with that but thanks for conversation and clearing my mind ;)
