### ISSUE TITLE
Manage breed timer confused by void maps

### ISSUE THREAD

**Issue by Sciencefreak** [zininzinin/AutoTrimps#131]
I like that "Manage breed timer" is keeping my breeding time around 30s,but starting void map which is reduceing breeding speed, convinced him to buy tons upgrades to speed up ...

Now my breeding time is at 7s outside void map, because he aimed for 30s inside void map. :(

As void map is only a few min, I is no good idea to set breeding speed according to it.

**Comment by spindrjr** [comment]
If breed timer were not adjusted for slow breed void map and you died in it, you would spend multiple minutes doing nothing. This is far worse than having too-fast of a breed time once you are done with them, and it will recover anyway.

**Comment by Sciencefreak** [comment]
This is only true after wave 70 when you can use genetics. Before it does not recover at all ...

But you are right that it is not that important because you have to reach 70 at least once to get anticipation.
