### ISSUE TITLE
Run time is 24h-based instead of absolute

### ISSUE THREAD

**Issue by Anahkiasen** [zininzinin/AutoTrimps#132]
No sure if this is a bug or just me not understanding the graph but Run Time's Y axis is setup like a 24h clock instead of being absolute. Which means a run that lasted 25h will be displayed as "01:00:00" because it resets at 24h:

![screen shot 2016-04-04 at 01 15 51](https://cloud.githubusercontent.com/assets/1321596/14235575/cbb52bba-fa02-11e5-9c6c-144b24238a08.png)

**Comment by spindrjr** [comment]
I don't see anything wrong with this.

**Comment by Anahkiasen** [comment]
As I said it's maybe me not understanding what the graph is actually displaying, isn't it the total time the run lasted?

**Comment by spindrjr** [comment]
Oh I see what you're saying, that it rolls over at 24h. Unfortunately I don't see a way to change this in looking briefly at the API.

**Comment by spindrjr** [comment]
I will keep this in mind if I find a way to fix it. Closing for now.
