### ISSUE TITLE
Problem with saving settings

### ISSUE THREAD

**Issue by morawcik** [zininzinin/AutoTrimps#136]
Hi.

Today when I change settings I get error (in browser console):
`Uncaught QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'autoTrimpSettings' exceeded the quota.`

pointed to AutoTrimps2.js line 163. When I reload page the settings are unchanged. Reinstall script not help.

**Comment by spindrjr** [comment]
Something about local storage being full. I don't know a lot about it. It might be directly AT related or not. You can try deleting the AT local storage by typing this into the console:

localStorage.removeItem(autoTrimpSettings)

Your settings will be wiped.

**Comment by morawcik** [comment]
I delete "allSaveData" item and now it work.
