### ISSUE TITLE
Breedfire wastes food firing and hiring geneticists

### ISSUE THREAD

**Issue by VaporwareII** [zininzinin/AutoTrimps#137]
when you are in breedfire, the geneticists hire/fire logic needs to be suspended. I suggest

```
    //otherwise, if we have some geneticists, start firing them
    else if ((targetBreed < getBreedTime() || 
                 targetBreed < getBreedTime(true)) && 
                 !game.jobs.Geneticist.locked && 
                  game.jobs.Geneticist.owned > 10
```

```
              **&& breedFire == false**) {
```

```
            safeBuyJob('Geneticist', -10);
            //debug('fired a geneticist');
```

**Comment by VaporwareII** [comment]
Tested that change locally, doesn't work as intended. Is there a way to nail down a breed time goal based on population and buy geneticists based on that?  The problem seems that the in-game timer is an inconsistent metric when you fire 2/3 of your workforce.  
Say you're running around level 80, at 30 sec gene timer, then you enter breedfire and now the timer is 12 sec and autotrimps starts hiring geneticists until you run out of food (5 or 6 hired for me).  Then you are within 2 sec of full and oh hey we have way too many geneticists, better fire them, but since you fire 10 at a time, you end up with fewer geneticists than you started with.  It's eating into the tributes.

**Comment by spindrjr** [comment]
Try refreshing now. I added a !breedFire check to hiring geneticists, so it
shouldn't hire them while breedfire is true.

**Comment by VaporwareII** [comment]
awesome, works great
