### ISSUE TITLE
Autotrimps is not buying any jobs during Trapper challenge

### ISSUE THREAD

**Issue by Anahkiasen** [zininzinin/AutoTrimps#139]
Not sure why, tried to look in the code but I didn't find anything, guessing it's related to the breeding time since that's the only thing that changes. 

[Save export](https://gist.githubusercontent.com/Anahkiasen/f1e4d4b87e33473b4fb97790e229b73a/raw/86848e46534c95bddc48eb123ba91b836345df70/gistfile1.txt)

I managed to kick it back on on this save, not sure how, but after manually buying enough jobs Autotrimps started working again. Not sure if it's that or just that early-Trapper AT is too busy buying/making traps to worry about jobs or something

**Comment by Anahkiasen** [comment]
Also seems Autofight is not working during this challenge, need to press "Fight" manually a lot, see [save](https://gist.githubusercontent.com/Anahkiasen/f24aebe86a527b76e3e0e3ddca4ed4ce/raw/b07b5205947765456b5598be8889dbdc3e118ecd/no-autofight.txt). Seems to be because AT never gets the trimps to their max limit so autofight doesn't kick in

**Comment by spindrjr** [comment]
Buying jobs and fighting is dependent upon you having certain population (namely, maximum population in all but a very few small cases). One-off challenges with special conditions will often act wonky with the script, but I have no plans to make any adjustments on account of them.

**Comment by Anahkiasen** [comment]
Didn't know that, saw a few challenges-related items in the changelogs, assumed the goal was 100% feature parity between challenges. Fair enough.
