### ISSUE TITLE
Logical issue with canbeatcell()

### ISSUE THREAD

**Issue by Ishakaru** [zininzinin/AutoTrimps#14]
Current version of canbeatcell() doesn't take into account post 60 mechanics, and doesn't really scale in any customize-able way. Recomend replacing current version with:

`````` javascript
function canBeatCell(cell) {
        // debug('Running canBeatCell - Enemy Health: ' + window.game.global.getEnemyHealth(cell.level, cell.name)+ ' My damage ' +window.calculateDamage(window.game.global.soldierCurrentAttack, true, true, true)+ ' and max hits: ' +maxHitsTillStuck());
        //return window.game.global.getEnemyAttack(cell.level, cell.name) < (getTotalDefence() * 0.75) && window.game.global.getEnemyHealth(cell.level, cell.name) < (window.calculateDamage(window.game.global.soldierCurrentAttack, true, true, true) * maxHitsTillStuck());

        var live=false;
        var hitsToTake=2;//2 hits feels low. Maybe a text box for the player to determine? 
        if (game.global.world>59)
        {//no less than 20% of enemies attack will be applied to trimps after block.
            var atk=window.game.global.getEnemyAttack(cell.level, cell.name);
            if (atk*0.8>window.game.global.soldierCurrentBlock )
            {
                atk = atk-window.game.global.soldierCurrentBlock;
            }
            else
            {
                atk*=0.2;
            }
            live=(window.game.global.soldierHealthMax)>atk*hitsToTake;
        }
        else
        {
            live=(window.game.global.getEnemyAttack(cell.level, cell.name)-window.game.global.soldierCurrentBlock)*hitsToTake<window.game.global.soldierHealthMax;
        }
        return live && window.game.global.getEnemyHealth(cell.level, cell.name) < (window.calculateDamage(window.game.global.soldierCurrentAttack, true, true, true) * maxHitsTillStuck());

    }```
``````

**Comment by Ishakaru** [comment]
Note of sorts. I don't know the code inside out. So there might be an issue with this. How do you take into account formations? Is the values used here before or after formations?

**Comment by WG-SpaceCoder** [comment]
All those game numbers take into account formations and everything. I'm already changing this logic around a bit so I'll add this in. Thanks!

**Comment by Ishakaru** [comment]
That's part of the concern I was having. Under Dom, health is halved. Under heap, *4. Reverse for attack. Block in either case is halved. Using the stance dance option will play havoc with this function(and the previous version), and by extension the logic surrounding entering and leaving maps.

**Comment by spindrjr** [comment]
I think higher up we might want a broader approach. Something like cells cleared in a time period and when the check fails, a fixed time to map before going back to zone. As part of this, we may want to be able to selectively run metal or garden maps.

**Comment by Ishakaru** [comment]
The current map management as a whole bugs the snot out of me. This function just happened to be the one where I was able to say "WRONG!" and provide a quick fix for it. I'll look into providing the functionality that I desire in regards to maps (type, when to run, how long(or times) to run, other options that may come up). Guess I'll have to look into how to do a pull request >.>

**Comment by WG-SpaceCoder** [comment]
Please refer to issue #22

**Comment by WG-SpaceCoder** [comment]
Hey @spindrjr can you take a look at this and merge his pull request? It looks good to me, but I just want to make sure.

**Comment by spindrjr** [comment]
Closing. Pull merged but v2 logic will be completely different.
