### ISSUE TITLE
Warpstation missing and map problems.. 

### ISSUE THREAD

**Issue by Snipe13051** [zininzinin/AutoTrimps#141]
Is “warpstation” new or why it’s not implemented in Auto Trimp?

Is there a way that auto trimp don’t buy every map at every stage? Even when i put on bestplate he buy it. So i'm all day long out of fragments because of that.

**Comment by Anahkiasen** [comment]
Is there a green border around Warpstations? If not that means some other housing is still better than them as Warpstations cost quite a lot when you first unlock them compared to Collectors and the rest

**Comment by genbtc** [comment]
Warpstation not missing. If you hover over "FirstGigastation" it says "how many warpstations it will buy before buying the first gigastation". and then Deltagigastation is how many extra it will buy every time you use a gigastation. The common formula is 20 + 2x. meaning 20 warpstations + 2*CurrentGigalevel

And if you set it to bestplate, it will buy everything up to and INCLUDING bestplate. so set it for something lower  if you want it to do less maps. The script does maps for Bestplate on levels 15/25/35, and for example Axe on 14/24/34, mace on 12/22/32 etc.
