### ISSUE TITLE
Wormholes break Helium/h Auto Portal

### ISSUE THREAD

**Issue by thefaint94** [zininzinin/AutoTrimps#144]
When I set Autoportal to He/h with any number of Max Wormholes, Autotrimps portals after zone 38 because all wormholes are purchased and He/h falls below previous.

**Comment by genbtc** [comment]
Added a new option:
Helium/Hr Buffer %. portal if your He/Hr drops by this amount of % lower

When using the He/Hr Autoportal, it will portal if your He/Hr drops by this amount of % lower than your best for current run, default is 0% (ie: set to 5 to portal at 95% of your best)
b6779f0c4acc9ef7367c34d2ffd4146e0b52a516
