### ISSUE TITLE
Autoportal/Crushed portals before completing BW

### ISSUE THREAD

**Issue by Anahkiasen** [zininzinin/AutoTrimps#147]
[Link to save](https://gist.github.com/Anahkiasen/f24aebe86a527b76e3e0e3ddca4ed4ce)

If you set Autoportal to Crushed, AT will portal right after zone 125 but before completing Bionic Wonderland, resulting in AT portaling before getting the helium bonus.

See the Graphs section, portals up to 81 were me portaling manually, compared to Autotrimps after that portaling right after 125 and losing the helium boost

EDIT : Note that in the save I switched to Helium/Hour/Crushed to see if it did it in that mode too but the early portal happened with Auto-portal set to "Crushed" directly

**Comment by genbtc** [comment]
I dont see how this would be the case, because in function autoPortal() , all the conditions require game.global.challengeActive to be false before portaling, so not running Bionic wonderland would mean the challenge is still active, and thus no portal. And that has been like that since forever.
