### ISSUE TITLE
Endless farming before void maps in early game

### ISSUE THREAD

**Issue by Ferboten** [zininzinin/AutoTrimps#149]
The script seems to want to farm before void maps forever in the early game. My last portal was around 47 and I tried setting it to do void maps at 30. Leaving it on over night and coming back to it, it was still farming maps before doing a void.

Looking into the issue it seems like it's spending metal only on damage and not health, so it will never finish farming.

**Comment by Sciencefreak** [comment]
have you disabled purchase of armor upgrades? You can also try to lower advanced settings of void difficulty check. This way it starts more early

**Comment by Ferboten** [comment]
Armor upgrades are enabled, and I lowered the difficulty check from 2 to 1 but it still didn't have enough. Maybe it's tuned for late game farming only?

**Comment by sasha-koss** [comment]
Farming for Voidmaps seems pretty broken.
It's farming/researching science with the "user" while it needs metal, and it's spending all resourcen on housing.
I'm sitting at 55B science and my next updrages cost about 20-55k science.

I guess the problem is that the bot buys housing before health while farming for void maps.

**Comment by genbtc** [comment]
@sasha-koss  The default behavior is to "user" research science when you have no Turkimp. Farming for voidmaps has nothing to do with science, its two sections of the script each doing its own thing. Farming for voidmaps relies totally on your health. The only "housing" that should impact the lack of health is Warpstations. Housing caps can be tuned by setting the variables in settings, such as FirstGiga+DeltaGiga. I will look into de-prioritizing Warpstations during "Farm" modes.
