### ISSUE TITLE
[enhancement] Auto Gigastation

### ISSUE THREAD

**Issue by HyperWeapon** [zininzinin/AutoTrimps#15]
Instead of having either a limit on Warpstations or no limit by entering some value or -1 into the box. I suggest that there will be two boxes. One labeled base Warpstations, and the other labeled delta Warpstations. Feel free to think of better names.
What I wish to be accomplished with these is for the script to check these values and use them to decide when to use a Gigastation. This would allow progression past zone 60 to be achieved far more automatically than it is now since the script doesn't do anything with Gigastations. 

The Pseudo Code should look something like...

``` javascript
get values from boxes;
//in this example lets assume 20 and 2 were obtained making the following values...
//baseWarpstations = 20;
//deltaWarpstations = 2;
If (currentWarpstations=>baseWarpstations+deltaWarpstations*currentGigastations)
{buy Gigastation;}
else
check if Warpstation can be bought
```

With this the script should buy 20 Warpstations followed by a Gigastation. Then 22 Warpstations followed by Gigastation and so on. Until the user either cannot progress due to bad inputs or no more Gigastations can be bought, and the user should portal.

**Comment by WG-SpaceCoder** [comment]
Stealing logic from @Belaith

**Comment by weltvagabund** [comment]
I would like to set the starting point and the Stepsize for this algorithm. If I do a run to 100 i would love to go with 15+1, but if I do a Deep run i might start with 20+5. Also I would like to adjust it at some point, if I notice it goes to slow or Quick

**Comment by spindrjr** [comment]
Latest v2 version has settings for first gigastation and delta gigastation.
