### ISSUE TITLE
Auto-recycle heirlooms

### ISSUE THREAD

**Issue by Anahkiasen** [zininzinin/AutoTrimps#158]
When farming for nullifium, it can get sometimes tedious to recycle one by one all the heirlooms. It would be nice if AutoTrimps had an option to automatically recycle all heirlooms when portaling, considering it already automatically keeps the best ones safe by carrying them.

**Comment by Anahkiasen** [comment]
3.4 added a "Recycle All" button to the Heirlooms screen so maybe the function underneath it could be called

**Comment by weltvagabund** [comment]
see the Auto heirloom Feature. This feature keeps the best Heirlooms after certain criteria, and all other Heirlooms are sold when you Portal. So I cant really understand your problem.

**Comment by Anahkiasen** [comment]
Hm, maybe a bug in Trimps cause I definitely still had all my heirlooms after portal. Will see if it happens again but yeah I do remember it doing it before now that you mention it

**Comment by Anahkiasen** [comment]
It already does indeed, don't know what happened, I completely bugged :o
