### ISSUE TITLE
Lead farming

### ISSUE THREAD

**Issue by DMathinator** [zininzinin/AutoTrimps#159]
When doing a lead run the script farms only on odd levels, which makes sense. However, it bases when to be done farming on the current zone, not the next zone, as far as I can tell. This can lead to major slowdowns in the later even levels of a lead run. I would suggest something like the following change to AutoTrimps2.js, starting at line 1351:

Old code:

``` javascript
if(!getPageSetting('DisableFarm')) {
    shouldFarm = shouldFarm ? getEnemyMaxHealth(game.global.world) / baseDamage > 10 : getEnemyMaxHealth(game.global.world) / baseDamage > 15;
}
```

New code:

``` javascript
if(!getPageSetting('DisableFarm')) {
    if(game.global.challengeActive == 'Lead') {
        shouldFarm = shouldFarm ? getEnemyMaxHealth(game.global.world + 1) / baseDamage > 10 : getEnemyMaxHealth(game.global.world + 1) / baseDamage > 15;
    else {
        shouldFarm = shouldFarm ? getEnemyMaxHealth(game.global.world) / baseDamage > 10 : getEnemyMaxHealth(game.global.world) / baseDamage > 15;
    }
}
```

Disclaimer: I'm new to looking at this code, so while I _think_ this should work, someone who knows what's going on in this whole section should probably check this before the change is made.

**Comment by genbtc** [comment]
Committed to 55978bb565889e53a76c6389da94429f040bdf0c
