### ISSUE TITLE
[QoL] Make a Bookmarked Version from the Script

### ISSUE THREAD

**Issue by weltvagabund** [zininzinin/AutoTrimps#16]
Analogue to https://github.com/superjerk/autotrimp enable to bookmark something like (see description of that Project)

```
1: Create a bookmark.
2: Edit bookmark.
3: Replace destination with:
javascript:with(document)(head.appendChild(createElement('script')).src='http://superjerk.github.io/autotrimp/autotrimp.js?d='+Date.now())._
```

to quickstart the Master Branch with one click.

**Comment by WG-SpaceCoder** [comment]
I actually want to amend this just a bit. I want the script to be able to work both ways. I have an idea of how to make it work, but I need to implement.

**Comment by WG-SpaceCoder** [comment]
Look for v2. Currently very wip. Only 2 basic features :/

**Comment by spindrjr** [comment]
Bookmarking enabled. Instructions in readme.
