### ISSUE TITLE
Max Trainers

### ISSUE THREAD

**Issue by c4080190** [zininzinin/AutoTrimps#163]
Would appreciate it if there was a way to set AutoTrimps to buy Trainers when it's cost is say <1% of Tribute's instead of a hard cap

**Comment by genbtc** [comment]
Agreed, will look into it.

**Comment by genbtc** [comment]
Currently beta testing this setting, on my genBTC fork of the repo:
New Setting: Cap Trainers to Tributes %. 
Only Buy a Trainer when its cost is, for example, LESS than X% of cost of a tribute, instead of a hard cap.

**Comment by genbtc** [comment]
implemented.
397ff4eefd038c633a9b37c2b6a7d89c14a8a425
