### ISSUE TITLE
Scientist, and lategame worker ratios! 

### ISSUE THREAD

**Issue by qwertgfda** [zininzinin/AutoTrimps#169]
Hello, i wonder if there would be possible to see changes to scientist early, and auto worker ratios lategame. 

If you got ver high carpentry, you fire all your scientist very early, this can slow down the game alot when you stop overkilling. 
IIs it possible to have it fire scientist on a set zone instead? 

Auto workers: Maybe some more setting here if possible, like alot more miner late.

**Comment by genbtc** [comment]
Agreed with you on both points. Any additional specific ways to achieve this are welcome. I have been using 1/1/20 ratio lategame for a while now and I am wondering what the cutoff should be to begin using that?

**Comment by KeySer87** [comment]
1/1/10 I belive many run with, 1/1/20 might also be good.
Maybe set workerratio to 1/1/10 or something when you hit ~1400 tribute.

**Comment by qwertgfda** [comment]
1/1/10 I belive many run with, 1/1/20 might also be good.
Maybe set workerratio to 1/1/10 or something when you hit ~1400 tribute.

**Comment by genbtc** [comment]
testing the results of
New EasyMode Worker Ratios, >1000 tributes = 1/1/10 and >1500 tributes = 1/2/22

On my own fork, will merge into main branch if successful.
