### ISSUE TITLE
[Bug] Manual Gathering switches always to Metal after Building

### ISSUE THREAD

**Issue by weltvagabund** [zininzinin/AutoTrimps#17]
In the current build the Auto gather always sets to Metal after building. 
Test case:
1. Activate Manual Gather
2. Activate Autobuy Buildings
3. Set Gather to Food
4. Let Autobuy Buildings buy a lot of Buildings so that Autogather helps
5. Auto gather jumps to Metal (not back to Food)

This happens for with and without Turk Imp (I tested at World 68)

**Comment by spindrjr** [comment]
Fixed.
