### ISSUE TITLE
v3.5.

### ISSUE THREAD

**Issue by Sciencefreak** [zininzinin/AutoTrimps#170]
Can anybody include new corrupted option into auto portal settings?

**Comment by Anahkiasen** [comment]
Also should Autobreed use the new Geneticistassist's logic?

**Comment by Sciencefreak** [comment]
autotrimp way of buying geneticists is much better, no need to change it. Adding corrupted should be really easy. Only one option has to be added, there is not even a need to change battle behaviour.

**Comment by genbtc** [comment]
added new corrupted challenge
