### ISSUE TITLE
Corrupted voidmaps.

### ISSUE THREAD

**Issue by qwertgfda** [zininzinin/AutoTrimps#172]
Hello. 
When you run corruped challange the Void Maps are much harder then normal void maps since they get corrupted.

A corrupted Voidmap at 190 got 6.8x dmg and 22.7x hp.

**Comment by qwertgfda** [comment]
A corrupted voidmap on 198 after corrupted ended on the other hand have 2.2x dmg and 7.4x hp

**Comment by genbtc** [comment]
Currently testing a fix for autostance so you don't just die. The "Void Difficulty Check" UI setting would still be the best way to adapt to Corrupted, both before and after the fix.

**Comment by Jonathonathon** [comment]
I've been noticing that auto stance just lets my trimps die before switching stances as well, thanks for looking into it.

**Comment by genbtc** [comment]
8/9/2016 Apply Void Difficulty check to Corrupted Void maps. 5c2d969d4e542189d0638349a056664f9196506c
and
7/20/2016 Big AutoStance changes merged from genBTC script: Handle Corruption.  87dd15ed63c224a5a18cee7691ec7919e96f4f06
