### ISSUE TITLE
Selecting unavailable challenge for auto-portal breaks script

### ISSUE THREAD

**Issue by jheard** [zininzinin/AutoTrimps#173]
If you select a challenge that is unavailable when setting up the auto-portal, the script gets stuck on the portal screen attempting to start that challenge. The game becomes unplayable with the AutoTrimps script enabled, and it is impossible to change the settings when it is disabled.

**Comment by genbtc** [comment]
simple answer: dont do that. im sure you can get back in to the settings and correct your mistake.

**Comment by jheard** [comment]
When the page loads it instantly starts trying to portal, and gets stuck on
that screen. There is no way to access the settings and change it. Is there
possibly something I could type in the dev console to change the setting
and fix it?

Edit: I fixed it by typing autoTrimpSettings.AutoPortal.selected = "off"
