### ISSUE TITLE
Spire breaks He/hr autoportal

### ISSUE THREAD

**Issue by deusnoctum** [zininzinin/AutoTrimps#175]
Currently, I hit maximum He/hr around zone 243.  However, when running corrupted there's a brief He/hr drop after zone 200 (probably because the Spire takes relatively long to complete).  When "autoportal on He/hr" is selected, the script autoportals at zone 201, which is way too early.

Could the script either a) ignore a He/hr drop at zone 200, or b) add a "minimum portal level" option for He/hr portaling?  I don't know if this problem exists for other challenge/zone combinations, so I'm not sure whether the added flexibility of b) is required.

**Comment by genbtc** [comment]
I am currently testing an option called HE/Hr Buffer, which you can set a Percentage for the HE/HR to drop by a certain percent and NOT portal. This sounds like the best solution to me

**Comment by genbtc** [comment]
Added a new option:
Helium/Hr Buffer %. portal if your He/Hr drops by this amount of % lower

When using the He/Hr Autoportal, it will portal if your He/Hr drops by this amount of % lower than your best for current run, default is 0% (ie: set to 5 to portal at 95% of your best)
b6779f0c4acc9ef7367c34d2ffd4146e0b52a516
