### ISSUE TITLE
Auto Heirloom upgrade

### ISSUE THREAD

**Issue by Anahkiasen** [zininzinin/AutoTrimps#177]
Currently the Auto-Heirloom keeps the best heirlooms and recycles the rest. It would be useful if there was an additional option to use the nullifium gained on each portal to auto-upgrade the kept heirlooms, since AT already has something to suggest what it thinks are the best things to spend Nullifium on.

cc @genbtc

**Comment by genbtc** [comment]
I can do this

**Comment by Anahkiasen** [comment]
I see this is done now, thanks!

**Comment by genbtc** [comment]
report any bugs so it can be implemented into the zinzin one soon when safe. not that i think there are any
