### ISSUE TITLE
Free workers are not set to jobs if quantity selected is "Max"

### ISSUE THREAD

**Issue by ivanpetrushev** [zininzinin/AutoTrimps#179]
Here are my AT settings: http://i.imgur.com/qtBqkdS.jpg

I have "Buy Jobs" set to green. If I have the quantifier set to "Max" jobs are not being updated: http://i.imgur.com/sVjbQqL.jpg

In the second I click something different than Max, i.e. +1, +10, jobs are being distributed okay.

**Comment by genbtc** [comment]
You were right, Fixed.
https://github.com/zininzinin/AutoTrimps/commit/03912e1a22ca23bd1747e2555af1091cfced0f41
