### ISSUE TITLE
Cant put worker ratio no matter what I do

### ISSUE THREAD

**Issue by KurtCocain** [zininzinin/AutoTrimps#180]
It keeps it to 1 no matter what i try.
farmer/LJ/Miner
Aways reset to 1 as soon as I enter a new number

**Comment by Jonathonathon** [comment]
Do you have Auto Worker Ratios enabled?  How much Helium do you have?

**Comment by KurtCocain** [comment]
I barely just started, this my 3rd run, 2 portals. but I figured since I will be afk 15~ hours starting tonight I could do the metal challenge. 

https://gyazo.com/a8bc1779585c5f219e8d56c36a42a559

Here is my settings

EDIT: Maybe I misunderstood the function? I thought it would ratio out workers for you,yknow just buy 5-2-3 or whatever. but now that you put it like this and I don't see a worker ration option in the scripts menu im guessing you get it later in the game?

**Comment by Jonathonathon** [comment]
Is this the link you're using?

javascript:with(document)(head.appendChild(createElement('script')).src='https://genbtc.github.io/AutoTrimps/AutoTrimps2.js')._

For the record, at that low a level, I run 1-1-1 Jobs as well.

**Comment by KurtCocain** [comment]
Its because it is keeping one for a miner which I don't want cause metal challenge. 

and oh, nope. it gave me the zinzinin link

**Comment by KurtCocain** [comment]
var script = document.createElement('script');
script.id = 'AutoTrimps-script';
script.src = 'https://zininzinin.github.io/AutoTrimps/AutoTrimps2.js')._;
document.head.appendChild(script);

**Comment by Jonathonathon** [comment]
Try the link I just gave you.  Disable Auto Worker Ratios and set the worker ratios to whatever you want, see if that works.

**Comment by KurtCocain** [comment]
It works, thanks alot.
I'll be using the other one from now on ^_^

**Comment by Jonathonathon** [comment]
Cool, glad you got it all sorted.  Cheers.

**Comment by genbtc** [comment]
This is confusing me. I dont know how you are missing the auto worker ratio button in the zininzinin script.

**Comment by genbtc** [comment]
I see what it is. You were missing the entire 6th column of buttons. As if you had resized the window to not wide enough, simply a matter of your screen size. Please report what resolution you were running and what device so we can prevent this....

**Comment by KurtCocain** [comment]
I was using the github.io, 1080px1920 fullsize screen(no F11).
Not sure what caused this. Everything is the same now except the menu has one more row squeezed in (and I emphasis on the ''squeeze'' here because before the menu would take the whole screen too)

**Comment by KurtCocain** [comment]
Figured everything out

EDIT
