### ISSUE TITLE
Why bother farming maps for prestige when there are unbought upgrades of the same?

### ISSUE THREAD

**Issue by jepler** [zininzinin/AutoTrimps#181]
Perhaps I just haven't configured autotrimps properly, but I notice that e.g., right this second I have 2 unbought (unaffordable) dagadder upgrades but autotrimps (full disclosure: from @genbtc's fork) will go in and spend time in maps for "prestige" anyway.

**Comment by KurtCocain** [comment]
Same here. But im kinda new to the game so i figured, yknow, maybe the bot knows whats best xD!
EDIT:
I found that using dynamic prestige is much more fluid
