### ISSUE TITLE
Mapology and lack of map credits

### ISSUE THREAD

**Issue by ivanpetrushev** [zininzinin/AutoTrimps#182]
When running the Mapology challenge the player can't run a map unless he has a map credit. AutoTrimps tries to run maps without having credits, resulting in a wall of those in the log:

>  11:31:15 You are all out of Map Credits! Clear some more zones to earn some more.

One solution is to disable AutoMap for parts of this challenge.

Can you detect if there are no more map credits and return to fighting in the World instead of trying to create a map?

**Comment by genbtc** [comment]
This is the first time somebody has complained, I am surprised it has never come up before so i asked around in chat. 
[11:57 AM] person1: I had no problems with mapology, just set prestige to dagger or mace
[11:57 AM] person1: Should run only 2 or 4 maps every 10 zones
[11:57 AM] person2: i had plenty of map credits spare at the end of the challenge
[11:58 AM] person2: so i didnt had any problems
Also by the time you read this you will be done with this challenge, and tbh AT does not run the challenges for you in the first place, but yes I can add what you said.

**Comment by genbtc** [comment]
743d840460dc0d4ef4f85ff7ff7bd2f7585561c7

**Comment by ivanpetrushev** [comment]
Yeah, I am done with it, and honestly it wasn't that bad. Just had to enable/disable AutoMaps here and there, but there is a quick button for this. Thank you, anyways!
