### ISSUE TITLE
Version 3.7 - Scrying AutoStance above L181

### ISSUE THREAD

**Issue by andrelim87** [zininzinin/AutoTrimps#184]
Edit: I understand that the script has been updated, but where can I change this setting in the UI? Or is this automatically done already?

I hope to be able to select the scrying stance above level 181 in order to gain dark essence. Is it possible to alter the autostance script to allow this?

**Comment by genbtc** [comment]
refresh. the settings are there.

**Comment by andrelim87** [comment]
Got it. Thanks a mill! It was exactly what I was looking for!
