### ISSUE TITLE
plot more then 10 last portals on graphs

### ISSUE THREAD

**Issue by Fregaa** [zininzinin/AutoTrimps#185]
Is there a way to do a input box asking for how many portals to log on graphs? I wish i could set it 20 or 30. I do 7 runs/day (avg 3.5h per portal) so this 10 last portal plot is just one day long. I Wish I could see the game evolution better.

**Comment by Jonathonathon** [comment]
Neat idea.  Could we also do a "hide all" button?  I often want to check the last portal's progress and have to select every single portal to hide all but the one I want.

**Comment by genbtc** [comment]
I have been preparing for this. I expanded graphs from 10 to 15. There is a limit on how much data can be stored (8MB in chrome) and previously this was about 10 portals. Now its about 15-20 but I dont want to exceed it or else thats going to break things. The buttons are also added now.
