### ISSUE TITLE
Automaps should create Gardens maps if Decay is completed

### ISSUE THREAD

**Issue by Anahkiasen** [zininzinin/AutoTrimps#188]
See related thread https://www.reddit.com/r/Trimps/comments/503lvr/mine_vs_garden/

**Comment by genbtc** [comment]
sorry, been busy, implemented this today in genBTC and i will backport it asap

**Comment by Jonathonathon** [comment]
Just a word of caution on this, Garden Maps only become more efficient if you have a high Motivation II:  https://www.reddit.com/r/Trimps/comments/503lvr/mine_vs_garden/d70zqun

genbtc, you may want to have some kind of check on this which looks at the players Motivation II to determine whether they should run Mountain or Garden.  The thread recommendation I found was pretty vague unfortunately, anywhere from 100 to 200.

**Comment by genbtc** [comment]
This now exists in the genBTC branch = https://github.com/zininzinin/AutoTrimps/issues/208
