### ISSUE TITLE
On reset, it was buying shed/barn before available.

### ISSUE THREAD

**Issue by sherkas** [zininzinin/AutoTrimps#190]
I noticed I just started this script and unlocked autoportal manually (via console).

I portal'ed and started fresh with the script (everything default and enabled pretty much).

It did fine until it had 1/3 of zone 1 cleared and it was starting to hit 300/500 wood. At that point it began to buy a shed however its not available in game so it would build it but then never work. So it would essentially waste those resources making the script unable to buy the miner and scientist upgrades.

**Comment by sherkas** [comment]
Im not sure on the condition for the upgrades (but I think... its on resource amount?) A simple dont buy a barn/shed/forge until you have a minimum 4-500 resource? The first resource fill up should trigger the expansions so maybe by addition a clause where it wont buy a upgrade until you have minimum 500 (even if the ratio says you should).

**Comment by genbtc** [comment]
yea I have seen this, and i fixed this on mine, I will try and find what I fixed and backport it to this repo.

**Comment by genbtc** [comment]
Fixed hopefully 7ed80c51a5b3b733bfe4b463d0810ca5e12150e3

**Comment by sherkas** [comment]
Just some feedback, in my particular case it worked!  Thanks for the update!
