### ISSUE TITLE
Run Map for Nursery if Home Detector I, II, and Blacksmithery Owned

### ISSUE THREAD

**Issue by Jonathonathon** [zininzinin/AutoTrimps#191]
An issue I'm running into recently, I'm not able to completely clear the Spire due to grabbing Nurseries too late.  There's no need to map since I have Home Detector I, Home Detector II, and Blacksmithery so Nurseries aren't picked up before the Spire.  

Can we have a button to run one map at whatever zone so they have enough time to be bought up before the Spire?  Thanks!

**Comment by Jonathonathon** [comment]
This might actually be a bit more complicated than that.  I've got someone testing on Reddit stating that AT still isn't purchasing geneticists even after forcing Nurseries.  I'll try to keep this thread up to date with our testing.

Quick Edit, apparently buying Genticists requires running 2 maps?  Not really sure on the specifics, but it may take 2 runs to trigger them for the Spire.

**Comment by Jonathonathon** [comment]
Started messing around with some code for this, it's heavy.  Here's the button idea I had in mind for NewUI.js:

createSetting('OneTimeMap','One Time Map Run','Run a Map once to unlock Nurseries, intended to help with the Spire for people that have Balcksmithery, runs map at Level 75','boolean',false,null,'genbtcadvancedSettings');

Running a map once at 75 should take care of all problems here.

**Comment by genbtc** [comment]
Tried to fix, runs a map (maybe 2) at level 60 (hardcoded), simplest way... Try this 115378e8c84325c6a6b65c11143c2c6d224cc51a

**Comment by Jonathonathon** [comment]
Awesome, thank you!

**Comment by Jonathonathon** [comment]
One minor thought I saw with this, in your if statement you may want to check and make sure that nurseries are actually locked before setting shoulddomaps to True.  That way if there's a change somewhere down the road (or someone runs it manually, or it gets added into the Housing Masteries, etc) it doesn't run needlessly.

Edit:  Also, is this getting merged into the main script?  Everyone that has Blacksmithery is going to have a similar issue.

**Comment by genbtc** [comment]
its not so simple to merge it into the zinin script. i put a check for game.buildings.Nursery.locked
