### ISSUE TITLE
Suggestion: Have a field for maximum scientists.

### ISSUE THREAD

**Issue by sherkas** [zininzinin/AutoTrimps#192]
Im pretty new to the running but one thing ive noticed is doing multiple 0-40 runs I really dont need more then 100 scientists. Most fields have maximums, I would love a maximum for scientist so that it follows the same ratios and what the script has currently, I just wish I could cap them so im not wasting trimps to help speed up my lower levels.

**Comment by genbtc** [comment]
e6853afb5be390807c87d9a947025f3d851ec700 will bring this into the zinin branch asap

**Comment by genbtc** [comment]
This now exists in the genBTC Branch @ https://github.com/zininzinin/AutoTrimps/issues/208
