### ISSUE TITLE
Randomly jumping to map screen with Maps=off

### ISSUE THREAD

**Issue by mnvoronin** [zininzinin/AutoTrimps#194]
I have automaps set to Off, but since yesterday AT randomly drops me to the maps screen.
Happens every couple of hours, and I haven't been able to establish the pattern.
Seen it happening from both the world zones and maps. It just goes to the map screen and stays there.
May be related to the other map issue, but I don't have it abandoning the army, just running to death and then jumping to the map.
Settings: http://prnt.sc/ch0bwr

**Comment by genbtc** [comment]
It was a new thing I put into the manage breed timer function to automatically abandon the army when it felt it could to respawn more anticipation stacks. I have just removed it because people like you are confused about what is happening.  Refresh.

**Comment by genbtc** [comment]
I had not considered it but this abandoning behavior would only work if Automaps was on, to take over the second half of "rejoining" the world/map fight. So i have removed it until i can figure out how to make it better.

**Comment by mnvoronin** [comment]
Seems to be working fine now, thanks!
