### ISSUE TITLE
Cant get bot to start gathering on portal reset.

### ISSUE THREAD

**Issue by sherkas** [zininzinin/AutoTrimps#195]
v2.1.2 stable is the version in chat.

It use to work, I dont think i've changed anything. If I manually gather the 30 wood/30 food it will kick in and start doing the first trap etc.

It just wont initiate the very first gathering of food/wood to restart. Any ways I can debug/fix?
I also left it for 10 minutes and it never clicked the first food button after 10 minutes. When I click the button it doesnt kick in... only when I harvest wood and you reach over 10 to build a trap.

**Comment by genbtc** [comment]
This now should be fixed in the genBTC branch: = https://github.com/zininzinin/AutoTrimps/issues/208
