### ISSUE TITLE
Option to disable Scryer stance just for Spire

### ISSUE THREAD

**Issue by zellyn1** [zininzinin/AutoTrimps#198]
I've been trying to figure out a way to leave Scryer stance functionality running without constantly failing to clear the Spire and can't figure out a reliable combination. It would be great to have a toggle that just says 'NEVER use Scryer in Spire'

**Comment by genbtc** [comment]
This now exists in the genBTC branch. https://github.com/zininzinin/AutoTrimps/issues/208
