### ISSUE TITLE
Running "The Wall" with bounty hunter mastery purchased

### ISSUE THREAD

**Issue by jean-malm** [zininzinin/AutoTrimps#201]
Not a huge deal, but considering it's a 100 cell map it takes some time to finish which builds up over a lot of runs.

**Comment by Jonathonathon** [comment]
You're not running the Wall?  Doesn't that give you Bounty which doubles your resource production for the rest of the world?  If genbtc does something with this, I really hope it's toggle-able.

**Comment by jean-malm** [comment]
bounty hunter mastery (the thing you buy for Dark Essences) gives you bounty automatically when you reach zone 15. At least it should ...

**Comment by Jonathonathon** [comment]
Oh I see, sorry I misunderstood.  That is weird, my game doesn't do this.  Do you have "Buy Shield Block" off and "Run Unique Maps" on?

**Comment by jean-malm** [comment]
I do. No point having shield block at higher levels and unique maps is still required for the autoportal feature (in my case at least since I do not have the corresponding mastery for the portal).

**Comment by jean-malm** [comment]
Seems to work properly now.
