### ISSUE TITLE
getCorruptScale is not defined in Trimps 3.81

### ISSUE THREAD

**Issue by EvidentlyCube** [zininzinin/AutoTrimps#202]
Since today's update my friend and I are getting the error `Uncaught ReferenceError: getCorruptScale is not defined` on corrupted zones which disabled better auto fight and provides us with a lot of unhappiness caused by lost He/h.

**Comment by Jonathonathon** [comment]
Having issues as well.  AutoTrimps isn't buying upgrades, weapons or armors.  Looks like buildings still work though, Gigas appear to be working alright.  Golden Helium is also still working.

**Update**:  As stated above, my Auto Fight also isn't working.  Additionally, MagnetoShriek isn't firing automatically.

**Comment by ShatteredSphere** [comment]
Also broken: Automaps does not run void maps.

**Comment by Uthboth** [comment]
3.811 was pushed today and is still causing the above issues. I dropped my custom portal to 199 and it didn't portal after I was past that zone. I tried with a new portal and no luck, even changing it to no custom portal it still passes the end of the corrupted challange.

**Comment by genbtc** [comment]
getCorruptScale has just been defined in commit# daadcaa5f1374a448c3e802eeb355535b1a7f5ce as of an hour ago. Please refresh and continue to report questionable behavior in this thread or a new report. Thank you.

**Comment by Jonathonathon** [comment]
So far so good for me, thanks genbtc!

**Comment by Uthboth** [comment]
Working again, thanks for the update.
