### ISSUE TITLE
Bug: Game Freezes when Automap

### ISSUE THREAD

**Issue by Day-Elven** [zininzinin/AutoTrimps#203]
Game freezes when I enter a map in auto mode.
1. This bug appeared today, I have never seen it before. Portalling did not solve the problem.
2. It appeares only starting from z73 (always at z73 and if you skip z73 by turning 'automaps' off for a while, it does not help).
3. It does not appear if you enter a map manually (with autotrimps turned off).

That's how it looks:
1. Game freezes. http://i.imgur.com/IUYeTz3.png
2. When you roll up browser window with a game and then return back to it, screen becomes white. http://i.imgur.com/Vj891tD.png
3. When you try to refresh the page, it does not work (page reloading takes infinite time).
4. The only way to unfreeze the game is to restart the browser, so the last save will be loaded.
5. Bug appears again at the same point so you can't progrees further with automaps enabled.

**Comment by genbtc** [comment]
There was a patch last night but there is no reason to explain this. I am unable to reproduce it. If you are still having problems join the discord channel @ https://discord.gg/0VbWe0dxB9kIfV2C or use this branch of the script. @ https://github.com/genbtc/AutoTrimps/raw/gh-pages/.user.js

**Comment by genbtc** [comment]
Actually i think I see the issue. It is likely related to you having 0 Farmers. I would advise you to have farmers, as the script was re-written to take workers away from Farmers in order to hire things like trainers, explorers, genetecists.

**Comment by Day-Elven** [comment]
Thanks, adding farmers helped. I think it was happened at z73 because geneticists appears at z70 and z73 is the closest zone to z70 while the script begins to run maps for equipment at zone *3, that's why it is 73 in this case. Also it have solved one more bug: when I had 0:0:1 workers ratio, my character was switching between manually gathering different types of resourses at a high speed (about 10 times per second). Now when I have 1:1:10000 workers ratio he is constantly at mining (as it is supposed to be I guess).

**Comment by genbtc** [comment]
Sorry I lost internet. I have since put a patch in that should help with 0 farmers if for some reason you insist on doing that.
