### ISSUE TITLE
Autofighting/Automapping broken

### ISSUE THREAD

**Issue by Zemlor** [zininzinin/AutoTrimps#204]
As title says, it stopped working and seems to be for everyone based on this [Reddit Thread](https://www.reddit.com/r/Trimps/comments/5bftz8/autotrimps_malfunction/)

**Comment by Day-Elven** [comment]
Same for me.

**Comment by alexp76** [comment]
I'm experiencing the same issue, turning off auto-map allows auto fight and auto stance to work again. Guess we have to hold tight for a fix.

**Comment by genbtc** [comment]
fixed. sorry
