### ISSUE TITLE
Allow auto-portal with decay challenge

### ISSUE THREAD

**Issue by Alxandr** [zininzinin/AutoTrimps#206]
Where I am in the game currently, I get a rather significant boost to helium/hr when starting with decay active. I would suggest adding the ability to select decay as starting challenge when doing he/hr autoportal.

**Comment by genbtc** [comment]
There, think i did it. 15a6344c67d157111cc9a375f47ac0e33f45f1db - Test it out. Make sure you are on the genBTC branch.

**Comment by Alxandr** [comment]
How do I use a different branch?

**Comment by Jonathonathon** [comment]
Make a new bookmark using the following link:

javascript:with(document)(head.appendChild(createElement('script')).src='https://genbtc.github.io/AutoTrimps/AutoTrimps2.js')._

**Comment by genbtc** [comment]
i wonder how he didnt know he was on the wrong branch when theres a gigantic message that says this everytime you reload
https://puu.sh/slRq8/106a9537ef.png
EDIT: Apparently, my message fails to display on kongregate.... wonderful.

**Comment by Alxandr** [comment]
FYI: I've never seen that message, and I don't use kongregate.
