### ISSUE TITLE
[QoL] Auto Pull Variables

### ISSUE THREAD

**Issue by weltvagabund** [zininzinin/AutoTrimps#21]
Copied from Reddit /u/Gr1pp717
One suggestion: instead of manually defining things like upgradeList you should pull those values from the game itself. e.g. var upgradeList = Object.keys(game.upgrades)

This way you wont have to manually keep your script in sync with their updates.

**Comment by WG-SpaceCoder** [comment]
Lol, I was just gunna add this from the reddit thread too. GG  

If enough people really want this I can do it, but right now I'm not.  

Implications...  
-Changes your game save export (this is good and bad. Marks your game that you automated, but it also will keep settings through export)  
-Only saves settings when trimps saves

**Comment by WG-SpaceCoder** [comment]
Let's plan on doing this during the UI rewrite. issue #24

**Comment by Ishakaru** [comment]
I'm good with this as long as there's an option to turn it off (to make a clean save).

**Comment by WG-SpaceCoder** [comment]
I decided to store in a single variable outside the game because I did not want to change the game save export. Do you guys really still want it to be a part of the game save?

**Comment by spindrjr** [comment]
I personally see no reason to change it.
