### ISSUE TITLE
Auto allocate, if set to "Dump into Looting II" will make helium disappear if Looting II is not unlocked.

### ISSUE THREAD

**Issue by danielaverso** [zininzinin/AutoTrimps#220]
As the title says, if you have "Dump into looting II" enabled and you have not yet unlocked Looting II, it seems the points still try to go towards Looting II and disappear as if used. I have roughly 2 million missing helium due to this.

**Comment by genbtc** [comment]
https://github.com/maurezen/AutoTrimps
