### ISSUE TITLE
[Feature] Turkimp gather Logic

### ISSUE THREAD

**Issue by weltvagabund** [zininzinin/AutoTrimps#23]
Suggestion from Reddit user /u/Aliamarc:

The Orginal Pseudo code is below:
*Actual variable name I located in Trimps.

```
If game.global.turkimpTimer* > 0
    If GatherWhileTurkimp.Selected = "Autoselect" then
        get gymCost
        get tributeCost
        gymTimer = ((gymCost - WoodOnHand) / WoodPerSecond) //Determines in seconds how long to reach the next gym
        tributeTimer = ((tributeCost - FoodOnHand) / FoodPerSecond) //Determines in seconds how long to reach the next tribute
        select case 
            case gymTimer > 1800 and gymTimer > tributeTimer //It takes more than 1800 seconds (30 mins) to get to next gym AND it takes longer to get the next gym than to get the next tribute
                set gather to wood
            case tributeTimer > 1800 and tributeTimer > gymTimer //It takes more than 1800 seconds (30 mins) to get to next tribute AND it takes longer to get the next tribute than to get the next gym
                set gather to food
            case else
                set gather to metal
      Else set gather to GatherWhileTurkimp.Selected
else set gather to Science

If ResearchItems.Count > 5 //5 is an arbitrary number, for want of a better determinant
    set gather to Science
    if ResearchItems() contains "Speedscience" or "Megascience" or "Efficiency"
        try to buy Speedscience
        try to buy Megascience
        try to buy Efficiency
    else try to buy ResearchItems().First    

```

**Comment by spindrjr** [comment]
I definitely think that a default to science gathering when no turkimp is active is a needed addition. With that in place it should be possible at some point to fire all scientists. This could be an option for automatic functionality.

However, I see no reason to switch to wood or food based on how close their respective upgrades are when metal is so much more important. IMO it should pick whichever resource has the highest gather rate to maximize the turkimp buff return (and assume that the user has set whichever resource is most important to them to have the most jobs = most gather rate) with a default/fallback on metal.

**Comment by spindrjr** [comment]
Latest push should default to gathering science if there is no turkimp up. I'm considering this done.
