### ISSUE TITLE
[Bug] Autobuy Buildings keeps on buying

### ISSUE THREAD

**Issue by weltvagabund** [zininzinin/AutoTrimps#26]
The Autobuy Buildings does not respect the Boxes with Limits anymore. It happyly goes over in the most recent master.

**Comment by spindrjr** [comment]
Was just waiting on new settings interface for this because I don't know how they will interact. If it gets delayed I'll fix the current one.

**Comment by weltvagabund** [comment]
well its the same with explorers and so on. but i will keep the bug reports for myself, until the new ui is there :)

**Comment by spindrjr** [comment]
Just hold off on the UI related ones I'd say. Most of the text boxes are not having any values pulled from them, check boxes don't do anything etc.
