### ISSUE TITLE
[QoL] Game Log Messages

### ISSUE THREAD

**Issue by weltvagabund** [zininzinin/AutoTrimps#27]
Put some Messages what you are doing in the Game Log, either in a extra Tab, or in the Main log.
Example: I just bought a Gym, or Autotrimps just bought a Greatsword Update

**Comment by spindrjr** [comment]
This stuff is shown. It's in the extra tab called 'console' :P I think that's probably better than having it swarm the game window. Do you have any particular reasons you would like it in the game's log?
