### ISSUE TITLE
[Bug] Auto Job disabling not working Properly

### ISSUE THREAD

**Issue by weltvagabund** [zininzinin/AutoTrimps#30]
After disabling the Auto Job Function I can only Hire or Fire 1 Trimp at the Time, even if I select 10, 100, or Custom. I gave up on trying to fire 1,3 Mio Lumberjacks :)

**Comment by weltvagabund** [comment]
Actually it does not work to select other amounts than 1 for buildings either.... Wanted to give the Gyms a Kick start at a new run and could only buy 1

**Comment by caj** [comment]
There's a workaround: if `Buy Buildings` and `Buy Jobs` are unchecked, you can buy in bulk again. If you're already on a bulk selection (`+100`, etc), you may need to toggle between one of the different numbers first (go to `+1` and then back to `+100` after the two automations have been disabled)

**Comment by spindrjr** [comment]
This should be fixed in the latest push. Both functions were setting buyAmt to 1 in order to use the game's cost check functions without resetting it.
