### ISSUE TITLE
[Bug/Feature]Handle Pop Up Messages

### ISSUE THREAD

**Issue by weltvagabund** [zininzinin/AutoTrimps#31]
Currently following Pop Up Messages are not handled correct:
Break the World World 59
Dangerous Purchases (Gigastations Upgrade)
Mini Robotrimp (125 and every 15 Levels thereafter)

Suggestion is, that these are closed automatically by the script, as soon as they Pop up.

**Comment by spindrjr** [comment]
Breaking world and dangerous purchases popups should be closed/ignored in latest build. If I'm reading the code correctly robotrimp is just a popup on the first acquisition, and is a regular tooltip that will be closed upon the next call of a close tooltip (of which there are many), so it shouldn't be an issue.
