### ISSUE TITLE
Add max amount of upgrades per weapon\armor tier

### ISSUE THREAD

**Issue by foopex** [zininzinin/AutoTrimps#32]
Suggest adding a box to define max level for weapons/armor

**Comment by spindrjr** [comment]
Can you give me an idea of the situation where you think this is required? Low level? High level? When new tiers are available soon?

I've thought about this before but couldn't decide in what situation the current system was damaging to progression.

**Comment by foopex** [comment]
I think mainly low level.  I seem to be at a place where i need a few equipment levels to keep going at a good pace, but only really need 4 or so before the new tier comes in to play.  I end up micromanaging the equipment while i let the script buy buildings and jobs.  If I just let the script go it can buy up to 30 levels of gear pretty quickly that I would have rather spent on buildings.

Does that help?

**Comment by weltvagabund** [comment]
I quote Grabarz19 from Reddit:

> In the early game, within the first few tiers or equipment, levels are so cheap you can easily afford >them, and they get you quicker to the next set of prestiges, so naturally you buy levels.
> 
> However, as you progress, the scaling of equipment has you unable to buy as many levels for as little relative cost as you could before. Meaning if you could afford 10 levels in Tier II easily, 10 levels in Tier III won't be as easy, and in Tier IV you might not even be able to get as many.
> 
> This creates a situation where around Tier V (for very early players) Tier VI or Tier VII (for players who are much later in the game) you stop being able to afford all the prestiges now, and they pile up in your upgrades tab. This is where buying levels in equipment is no longer worth it.
> 
> In general, it's not worth buying levels if you have spare prestiges to buy. This is because when you prestige equipment with levels you lose the bonus gain from the levels, which means you effectively wasted metal. And some people argue that it's not wasted when it speeds you up, and while that's true, it is wasted if you have prestiges lying around, which also speed you up.
> 
> Example: You have Equipment 1 with level 1 that costs 100 to upgrade and 1500 to prestige. If you buy that level, the equipment will give 2x its original output. If you buy the prestige now, you paid 1600 and it now gives ~12x its original output. If you never bought that level, you paid 1500 and it gives the same final output. You wasted 100 metal.

If we take this we can derive following rule:

```
IF unbought_equipment=true then only Prestige() 
else 
buy_Equipment
Buy Equipment until Level =(10-Prestige Level) or until EquipmentCost>=PrestigeCost
```

This should give a quick Start and in the long run only Prestige Upgrades

**Comment by foopex** [comment]
Oh that looks way better than setting numbers manually.

**Comment by spindrjr** [comment]
Well, if upgrades are sitting and available (ie. not still 'locked' in a map) it already prioritizes them. I just loaded up a random save of mine at lvl. 130. The next thing it wants to buy is a dagger level, taking it from level 1 to 2 for 10.6 Dc metal which will add 8.49 Sp attack. There is no dagger prestige available right now or it would prioritize that (if it was the next best deal). 

There are other weapon prestige available, such as mace, but the attack per metal given by them is less than leveling the dagger once. Megamace is 17.7 Dc metal for 12.7 Sp attack, ratio of .7175 attack/metal, while the dagger level is 8.49/10.6 = .8009.

This all seems to make sense to me. Do you guys think the script should behave differently here?

**Comment by spindrjr** [comment]
Or is it just the early game we think is wrong?

**Comment by weltvagabund** [comment]
I just tested it at Lvl 86 With some Upgrades in Backog, and it still bought equipment. That is not Optimal.
 I think there should be a hard Limit to Upgrades, and that is 10! (Especially for Low Levels)
Additionally It should not buy equipment if Prestige items are available.
else there should be a cost sanity check in, like above mentioned.

**Comment by spindrjr** [comment]
The equipment it bought had a prestige available? Can you pastebin an export for me?

**Comment by foopex** [comment]
The current behavior works fine IMO, as long as the next tier is available for purchase and it can compare the cost/benefit.  I just want to keep it from buying dozens of upgrades when it cannot make that comparison.  I think it only really matters in the very early game.

**Comment by weltvagabund** [comment]
http://pastebin.com/R1u6fB5R
Switch on the Option and it starts buying daggers and so on

**Comment by spindrjr** [comment]
Awesome thanks I see what you're talking about. I'll look into it.

**Comment by spindrjr** [comment]
A basic version of this is in the latest build. It limits equipment level to 10-prestige. It does this regardless of if a prestige is waiting for purchase in your upgrades. The initial few runs I used it on it seemed to slow me down by a fair bit in reaching the prison on an electricity run (5-10 min slower at roughly 2 hours to reach) and in final He/hr at zone 120-130 (few thousand/hr lower). It seems to lose ground grinding for the next prestige in a map where purchasing equipment levels would have pushed through. It might be that instances where waiting for the prestige would be beneficial are outweighed by instances where buying the equipment is better. Try it out and let me know any feedback. I'll work on 10 maps max next. It might behave a bit better with that.

**Comment by foopex** [comment]
I'll be portalling tonight and I'll time it.  I am still very early game, having between 2k-3k helium to play with.  Once prestiges start piling up for me after zone 25 and it ends up self limiting.

I'm curious how the 10 maps max suggestion would work out.  The script spent 3 hours running a zone 13 map last night after my portal for some reason, I had to interrupt it and it quickly climbed to zone 20.

**Comment by spindrjr** [comment]
The 10 maps thing should really only come into play toward the end of your run, and help you push some extra zones. Or if you are going past breaking the world it should smooth out pushing through zone 59. The reason I say it might behave better with that is it would limit it to 10x map bonus grinding for a prestige, then force it to move on (to a higher gather rate presumably).

Not sure why your thing got stuck. It must have thought that it didn't have enough health or hp (did it have stuff to buy? eg. you didn't turn off buying stuff?). But in that case it would have hit a 10x bonus and moved back to world if that feature was in.

**Comment by weltvagabund** [comment]
Guys, can we stay on Topic. Discuss Maps in the Maps Topic.
Equipment Feedback:
1. Equipment doesn't seem to be bought Instantly. Why does it take minutes to buy Levels of Prestige II Equipment? I have millions of metal and can buy this manually in seconds. Same for Prestige 3 to 5
2. The math is off. It should only buy 8 Levels of Prestige 2 not 9. It is offset for all Levels i saw.
3. It should only buy levels if there is no Prestiges in the backlog. It is a waste of resources if there is a backlog.

**Comment by spindrjr** [comment]
1: I just watched a fresh portal up to dagger prestige 3 and everything seemed to be working. It will not buy some levels of equipment if it has decided that a prestige is more efficient (designated by a yellow , or maybe it's orange, outline on the equipment for which it wants to buy the prestige for next as the most efficient purchase). The prestige purchase might be held up by gems or science. Are you seeing something different?

2: Those are the numbers I intended.

3: This is sort of the point of the limit on equipment levels, to reign in the excesses that might be spent when there is a prestige available. Adding logic beyond the current gets messy fast, as this is all tied up in a pretty convoluted area of the code. As of right now I'm still unconvinced on the whole idea so I'm not up for it.

**Comment by spindrjr** [comment]
Some data: at about 8.5M helium, started simultaneous runs (one in private browser) of the same game: electricity challenge, 4:3:1 miner:farmer:lumber 22+3 gigas, one with limit equipment (henceforth 'limit') on, the other off. Limit was slower for this particular game, clearing prison about 10 minutes behind nolimit. Around zone 138-139 limit seemed to be about 15 minutes behind nolimit (at about 4.5 hours total run time), but it did seem like it was maybe closing the gap by a little (less than a minute per zone, but I only took one data point for that). Assuming it was closing the gap by the amount I measured, it probably would have pulled even within 2-3 hours at the rate I was clearing. This was already well into declining helium per hour stages.

In this particular case my conclusion would be limit not good for he/hr here, maybe better for deep pushes, and in which case maybe better to turn on later in the run(though fairly insignificant considering the amount of time most people deep push).

**Comment by weltvagabund** [comment]
![capture](https://cloud.githubusercontent.com/assets/16541329/12447716/c71e023c-bf71-11e5-8761-e71a1cb720c3.PNG)
Why is the script not buying all the Metal Equipment right away? I clearly have enough resources
Edit: I am expecting all Items on Level 9 like the Dagger

**Comment by spindrjr** [comment]
In this case it has decided that leveling dagger is the next best DPS item, but you have limit on so it is waiting to prestige it. Health items are not being bought because the internal checks for health are currently passing.
