### ISSUE TITLE
[Bug] Geneticist Interaction Broken

### ISSUE THREAD

**Issue by HyperWeapon** [zininzinin/AutoTrimps#38]
Probably should have reported this earlier, but was waiting until v2 was more or less stable.
The script simply doesn't acknowledge Geneticists for me and never has. It doesn't buy or sell them to meet my Genetics Timer setting resulting in a lot of missing health.

**Comment by spindrjr** [comment]
That is very weird. There's basically no way to turn that feature off. So when you hit level 70 and unlock geneticists, you see geneticist as an option under jobs, but the script never buys any? And you have your timer set higher than the current game's breed timer?

Would you be able to provide me a pastebin of your export?

**Comment by HyperWeapon** [comment]
http://pastebin.com/9RrEKMYp

Yes and Yes. The option has never worked for me. Not in v1, and still not in v2. I'm using Firefox if that makes any difference.

**Comment by spindrjr** [comment]
Well I guess there is a way to turn it off. It apparently requires the game's core breed timer function to be enabled. Go into your game settings and turn it on (it was added fairly recently). I'm not sure I want to change that and I assume you're not opposed to having that option turned on.

**Comment by HyperWeapon** [comment]
Oh, I didn't even attempt to toggle that option in the core game. Thank you very much. Enabling it fixed my Genetics Timer.
Might be a good idea to add a note about this to the Readme.

**Comment by spindrjr** [comment]
Good idea. A writeup of the settings and basic script behavior is on my list.
