### ISSUE TITLE
[Suggestion] Option to Enable/Disable Certain Unique Maps

### ISSUE THREAD

**Issue by HyperWeapon** [zininzinin/AutoTrimps#39]
As the title says. It would be rather nice if the script just skipped certain unique maps while still running others. The Wall should never be skipped for example, yet others can be.
More specifically, "The Block", "Dimension of Anger", & "The Prison".

Running The Block when not needing the upgrade is a waste of time, and having the upgrade unlocked even though I never plan on using it is somewhat annoying to look at sometimes. 
Also running the Dimension of Anger when not immediately using a portal afterwards is also a waste of time. Yes, the time lost is minimal with lots of helium, but not having more options is never bad.
And with the recent change to The Prison's Key, and the map being always red after the first completion, the script seems to consider it completed even when it hasn't been. This causes Electricity runs to by extended further than necessary if not manually completed.

**Comment by spindrjr** [comment]
I pushed an update within the last 8 hours that filled in a lot of missing unique map logic in v2 (which was basically non-existent and not trying to run anything) If you have autorun unique maps on, it should only run maps like prison during challenges that require it (with a small difficulty check for safety), only runs the block if needed for a challenge or you have selected 'buy shieldblock' option. 

I think it meets all your criteria excepting that running DOA is not put off except if the difficulty check fails.

**Comment by spindrjr** [comment]
Though I should note that I have not had time to test most of the logic, so give a whirl and let me know if you have any issues.

**Comment by HyperWeapon** [comment]
After doing a run to 120 all the map logic seems fine. Especially pre-world breaking was practically perfect. Unique Map logic worked just as you described.
