### ISSUE TITLE
[Bug] Cant set genetics timer / Worker Ratio

### ISSUE THREAD

**Issue by weltvagabund** [zininzinin/AutoTrimps#41]
I am at level 129 and tried to set the genetics timer from 30s to 20s, but it doesnt accept my choice, and switches back to 30 sec.
After Portaling, it is still the same, only that it seems to be hardcoded to 3 Seconds. I checked Farming/Mining to and the ratios there are also hardcoded. I assume this has to maybe do with easy mode, but still it is kind of annoying, or at least there should be info about this behaviour in the tooltip.
Also after deactivating easy mode i can only set workers, not genetics.....

**Comment by WG-SpaceCoder** [comment]
@weltvagabund try unchecking "easy mode" as easy mode will auto change settings based on progress. Also make sure you are using v2.

**Comment by spindrjr** [comment]
Option doing this is 'Manage Breed Timer'. Are there conditions where you regularly want 20s timer?

**Comment by weltvagabund** [comment]
Yes, now it works.... partly my fault. I didnt F5 before. spindrjrs option does the trick
