### ISSUE TITLE
V2 Hire Scientists option

### ISSUE THREAD

**Issue by foopex** [zininzinin/AutoTrimps#43]
The Hire Scientists option does not appear to work

**Comment by spindrjr** [comment]
Yea I am aware of this I just can't figure out what I want to do with it. Were you hoping it was going to stop buying scientists for you? Or just testing stuff?

**Comment by foopex** [comment]
Hoping it would stop buying scientists.

**Comment by spindrjr** [comment]
I'll go ahead and make it do that for the next build I push.
