### ISSUE TITLE
Geneticist Timer

### ISSUE THREAD

**Issue by Steve-Walsh** [zininzinin/AutoTrimps#46]
I'm unable to change the number in this field within the new UI you have implemented used both tampermonkey script and adding it to a tab. I have also open console within Google Chrome and ran the command you advised at bottom of read me. This allowed me to change it once, but since I'm unable to alter it again. 

The box does pop up and I change the number and hit apply this is then not reflected within the Automation tab.

**Comment by weltvagabund** [comment]
Are you sure you have deactivated the Setting: Manage Breed Timer. ELse it will be set by the Script.
@spindrjr we should change the Tooltip to contain this information for the Jobs and the Timer

**Comment by Steve-Walsh** [comment]
Yeah, I didn't see that option, turned it off and it allowed me to changed it. Thanks for the help

**Comment by spindrjr** [comment]
We just like to make things a mystery! I've cleared up the tooltips for these two options a bit in my next build.

**Comment by weltvagabund** [comment]
You rock!
