### ISSUE TITLE
Auto Fight depleting trimps in early game

### ISSUE THREAD

**Issue by darmichar** [zininzinin/AutoTrimps#51]
I thought there used to be code that would maintain a minimum amount of trimps.  Auto-fight is now using all available trimps until the breed timer hits 0.01

I have turned off everything and am unable to get auto-fight to stop.  Trapping isn't fast enough to keep trimp count up versus auto-fight usage.

**Comment by darmichar** [comment]
...and for whatever reason, it started holding trimps at Zone 5.

**Comment by spindrjr** [comment]
I pushed a fix that should hopefully prevent it from using all your trimps. Worst case, it now obeys the manualGather setting so you can turn it off.
