### ISSUE TITLE
Checking Traps

### ISSUE THREAD

**Issue by foopex** [zininzinin/AutoTrimps#53]
Script quit checking traps as needed when I updated it today.

Settings:
http://puu.sh/mEVZ1/fb3470b9c2.png
Export:
http://pastebin.ubuntu.com/14595466/

It looks like it really wants to gather science even though I have way more than I need to cover upgrades in queue.

**Comment by foopex** [comment]
Update: It did start checking traps again, so it seems that it sometimes wants to prioritize science over checking traps even though I far more than I needed to cover my upgrades in queue.

**Comment by WG-SpaceCoder** [comment]
What version?

**Comment by foopex** [comment]
V2, sorry.

**Comment by foopex** [comment]
After rewiewing the code it appears that trap checking to help low level breed time has been removed entirely.

**Comment by spindrjr** [comment]
Unless I'm going crazy I don't think auto trap checking was ever in v2. I know I did mess around with some trap <b>building</b> but not any checking to my knowledge. The manualLabor building check used to see if Trap was the first item in the queue, and if so it would only switch to building if the queue was greater than 1 (eg. there was something other than a trap, which is maybe from trapstorm, to build). The current code should behave no differently.

**Comment by foopex** [comment]
Ok I must have only noticed this after portalling when I moved from V1 to V2.
