### ISSUE TITLE
Gen Timer broken with breed times turned off.

### ISSUE THREAD

**Issue by Ishakaru** [zininzinin/AutoTrimps#54]
getBreedtime() returns 0 with breed time turned off in the settings.

**Comment by spindrjr** [comment]
I was leaving this in as a way to turn off auto-geneticists if people really wanted. But a check to turn the setting on once in the initialization would probably be good.

**Comment by Ishakaru** [comment]
Doesn't setting Geneticist timer to 0 achieve that functionality... in a manner that the user can see?

**Comment by spindrjr** [comment]
Yea I suppose it would. I just looked at it and it appears that zin just copy pasted the source code along with the option check, which we don't care about obviously. (can you tell this is the first time I've look at that function?). Should be fixed in latest push.
