### ISSUE TITLE
[Bug]Auto fight wastes potential breed time.

### ISSUE THREAD

**Issue by Ishakaru** [zininzinin/AutoTrimps#55]
Right now, fight is triggered inconsistently with regards to the game. Most times its checking to see if you have a full bar, which does not seem to be the intent of the code. If you have 1M trimps fight will be triggered at 999.999k trimps which is MUCH less than a tick of breed time. At 20 trimps, fight will be triggered at 19 trimps. This could be several seconds of breed time.

``` javascript
if (game.upgrades.Battle.done && !game.global.fighting && game.global.gridArray.length !== 0 &&
 !game.global.preMapsActive && (game.resources.trimps.realMax() <= 
game.resources.trimps.owned + 1 || game.global.soldierHealth > 0 || lowLevelFight )) {
            fightManual();

          } 
}

game.resources.trimps.owned + 1 should be replaced by

game.resources.trimps.owned+(((game.portal.Coordinated.level) ? 
game.portal.Coordinated.currentSend : trimps.maxSoldiers)/(getBreedTime()+0.001))*0.2
```

This takes in all factors.The fight should be triggered <0.2 seconds before the bar is full. I expect that in some cases it will be triggered <0.1 seconds of a full bar, which would would be rounded up to 0.1 seconds by the game, thereby wasting potential breed time, and time that could be used fighting.

Note: a debugging effort may be deployed to double check that fight is indeed triggered before the bar is 100%. If it is, the '0.2' can be increased to what ever level is needed. This is only a concern due to the log nature of breeding.

**Comment by spindrjr** [comment]
I think I get the idea behind this but I don't think you will get any benefit from it (outside of low helium levels?) unless you spread it to stance dance logic. Basically all the fights are started when the existing army dies, not when the breed bar fills. If you spread the logic to the stance dance, and have it dance back to dominance/none stance which is at 0 or less HP to kill the army you might be able to squeeze some seconds out while pushing towards the end of a run, but ideally we are trying to avoid ever leaving damage stance in the first place (and probably don't for the entire 'speed' section of a run).

In any case, I'll leave this up to zin.

**Comment by Ishakaru** [comment]
It's used any time that the fighting group dies before the next group is ready to go. At about 1 mil-ish there are times during the run where this is true. Most of the time it isn't though like you said. This is due to the conservative approach to automapping. It may be noted that I'm running electricity runs atm, don't know how much that matters. Though the same idea may be applied to Nom runs.
