### ISSUE TITLE
Graph UI doest disappear when choosing settings or automation menu

### ISSUE THREAD

**Issue by fayumot** [zininzinin/AutoTrimps#63]
Basically with the the graph tab open clicking either the automation or settings button result to the graph UI pushing the automation or settings menu upwards.

**Comment by spindrjr** [comment]
Fixed in latest push. Base game settings can still stack on top of graphs but not sure if I can change that without combining the injections. Hopefully it's not enough to push the buttons off the screen for most resolutions.
