### ISSUE TITLE
[Optimisation] Genetics/Breed Timer/Anticipation & Nom

### ISSUE THREAD

**Issue by weltvagabund** [zininzinin/AutoTrimps#64]
Nom makes you loose 5% Health per Attack. Which Means the Breed Timer is regulated to 10 Seconds. If you now apply the Stance Dance to it, you will switch latest after 10s from Dominance to Normal, and double your HP, which means you will last another 5s, when you switch to Heap and again double your HP. This is of course not taking Enemy damage into account.

My suggestion is to increase the wanted Breed time to 15 or 20s, so that we have more from the Anticipation Perk.

edit: of Course this applies only after Levels 60 & 70

**Comment by spindrjr** [comment]
I did some napkin math to see if this was worth it and it looks like damage-wise it breaks even. I'm unsure exactly if it would be positive or negative for progression in other regards (slightly more health, different numbers for progression checks). I might test it out on my own branch sometime soon after I settle down my toxicity numbers.

**Comment by weltvagabund** [comment]
That very well be true. But it is less Nom Ticks on the Impropabilities, which makes them easier to kill....especially in the few very last levels.

**Comment by spindrjr** [comment]
Set to I think 14 sec in the latest release. 15 I saw going into heap/downtime too much for my tastes.
