### ISSUE TITLE
Graph can't be interacted with

### ISSUE THREAD

**Issue by HyperWeapon** [zininzinin/AutoTrimps#66]
When interacting with the graph such as hiding an individual run or changing pages to see which run is my newest it quickly resets to having all graphs unhidden and viewing page one.

Now that I have 20 portals recorded on the graph the runs are starting to blend together, and it is difficult to tell if using different values for base and delta gigastation are helpful or not. Before I could just hover over the most recent portal on the list on the right, but now that it has multiple pages I don't have time to change page and hover before it resets after a second.

Not sure if this is a legitimate bug or a limitation with highcharts.

**Comment by spindrjr** [comment]
I made some QOL changes to graphs in the latest push. They should only auto-update every 10 seconds now. This at least gives you 10 seconds to look at stuff. There is also now a clear data button that clears all data except the current run. I'll close this issue but if you have any suggestions etc. feel free to open a new one.
