### ISSUE TITLE
[bug]Tooltip being hidden while in use.

### ISSUE THREAD

**Issue by Ishakaru** [zininzinin/AutoTrimps#69]
Is there a reason that I can't discern for the tool tip to be hidden when auto buying things? It gets in the way when I try to do things... like use the custom autoportal function...

**Comment by spindrjr** [comment]
I haven't come up with an easy way to fix this yet so it will probably be around for now. Just FYI. Maybe Zin knows something.

**Comment by spindrjr** [comment]
This problem is not how I remember it. I think it was just one rogue entry using cancelTooltip instead of hide. This should hopefully prevent it from closing value input popups when upgrading equipment.
