### ISSUE TITLE
[Minor Bug] Auto Trimp Jobs

### ISSUE THREAD

**Issue by weltvagabund** [zininzinin/AutoTrimps#7]
I actually managed to break it :) 
See Test Scenario: Level 15 about 25k Trimps max employed. Pulled Script with Changes in #6 
1. Switched to Premaps Screen (to Disable any Resource Loot) 
2. Disabled Auto hiring 
3. Fired everybody 
4. Set Limits for Farmers to 0 5. Enabled unlimeted Hiring for all other Jobs. 
6. Reached Zero on Food 
7. All Hiring Stopped -> Your Fix works for Explorers, Trainers, Scientists, Lumber and Metal 
8. Hired 1 Farmer -> Hiring happened only when Food was available :) 
9. Stopped everything. Fired everyone, set Limits again properly (-1 on Resource gatherers, 100 Science, 50 Explorer) 
10. Ended somehow with 105 Scientists.

Don't know why those extra scientists, but i would file this only as Minor Bug

**Comment by WG-SpaceCoder** [comment]
Check current version. Should be fixed.

**Comment by weltvagabund** [comment]
Can not recreate, is fixed
