### ISSUE TITLE
Game start/prestige is a bit wonky

### ISSUE THREAD

**Issue by marvin-bitterlich** [zininzinin/AutoTrimps#80]
When you prestige and let the skript do the work, it does some wonky things:
- not gathering stuff (at least not the visible/unlocked stuff) and stops gathering that
- Removes all but one Farmer/Lumberjack until you get the miner
- Better auto fight kills all trimps and breeding comes to a stand still (and combined with fireing all workers, no production at all)
- Important upgrades are ignored in favor of Gym and Shield. At the beginning it would be best to have (perhaps a special case) where you ignore fighting benefits for the first x minutes of game time or the first 1-2 stages.

I'm playing with only 30 helium so it could be that a bit, but most issues are really obvious

**Comment by spindrjr** [comment]
Thanks. I'm going to look into making some very low/early game improvements that address some of these issues but stuff like buying gym/shield before something else I likely will not change any time soon.

**Comment by spindrjr** [comment]
RE: Important upgrades are ignored in favor of Gym and Shield

In working on this, I made it so nothing is bought until Miners and Scientists are unlocked. Did you have any other upgrades in mind that you feel it it needs before buying other stuff?

**Comment by marvin-bitterlich** [comment]
I would think focusing on upgrades before using equipment at all would be nice. Like for the first levels, just first save for Cooperation and SpeedMining (and the others) before spending your iron on weapons. I think you already have code for something like this. but only buy equip if your (non-equip) upgrades can all be bought with the remaining metal. That would be nice I think.

PS:
And having a cache clear button would be nice, for me on chrome (with userscript) it seems to cache aggressively... So I have to visit the source url and refresh there for it to update

**Comment by spindrjr** [comment]
I'll keep that stuff in mind. In the mean time, I just pushed a new version with support for trapping and the previously mentioned delays on purchases until Miners and Scientists are unlocked. Hopefully this makes you early game a bit better.

PS: I know basically nothing about localStorage or caching so I'm not gonna mess around with that. Are you using the latest URL? (https://zininzinin.github.io/AutoTrimps/AutoTrimps2.js). I haven't had any caching issues that I recall since switching to this URL when using tampermonkey.

**Comment by marvin-bitterlich** [comment]
Seems like force reload works on the cache and I perhaps have not noticed until now... 
Thanks a lot for the fix! Will drop in with new suggestions in time :)
