### ISSUE TITLE
Suggestion: Separate 'Auto Portal' and Challenge

### ISSUE THREAD

**Issue by Invariel** [zininzinin/AutoTrimps#81]
It would be nice to be able to configure the script to auto-portal at (for example) Zone 90, while re-starting in Electricity.

**Comment by spindrjr** [comment]
I assume you are running to 90 because your he/hour continues to increase after clearing electricity. If that is the case you can choose helium/hour setting which has an associated challenge setting.

Or is there some other reason you are continuing to 90?

**Comment by Invariel** [comment]
Ah, I see.  Thank you.
