### ISSUE TITLE
Possible game-freezing issue

### ISSUE THREAD

**Issue by spindrjr** [zininzinin/AutoTrimps#82]
I have run into this once and there have been a couple reports of the script/game freezing, possibly related to void maps (so around when you have your void maps set to run, or possibly if you picked up a void map after you ran the others). I have been unable to reproduce it nor run into it organically since.

Please let me know if you encounter this and provide any details (zone number, was it possibly trying to do void maps, an export if you can) you can.

Thanks.

**Comment by nelseric** [comment]
I've experienced this issue in zone 70, usually 10 imps or so after entering the zone. I was able to get a debugger open before it froze and when I paused, it was in the function that buys nurseries I think. I tried to resume and pause again to see if it would be the same, but it broke more than usual.

I got around the issue buy firing some workers, so this may have something to do with hiring geneticists.

**Comment by spindrjr** [comment]
Typically most hard-freezes like that are from an infinite loop, right? (you probably know better than me)
I just pushed a new version where I removed a while loop related to firing geneticists to speed breed timer, but you shouldn't have been in that loop before having geneticists.

There are two while loops in the hiring of trainers and explorers that don't look like they could go infinite but could be easily removed.

**Comment by nelseric** [comment]
I have a feeling it might have been something going wrong with the update to 2.9, since I think I could buy geneticists before / early in zone 70. Either way, I haven't seen the bug again, so I can't confirm anything

**Comment by weltvagabund** [comment]
I encountered erratic behavior after doing Void Maps on Tox Runs. I usually run the maps on Lvl 160, but it runs all Levels after with Max Tox batches, before it continues to the next Level. SO basically it is running the last five Levels all to 1500 Tox Stacks, even the Parameters shouldfarm=false and HeliumGrowth=false. I go dig in the code and if I find the exact spot where it goes wrong i set a marker.

edit: I think Line 1055 in Autotrimps2.js is not resetting properly, after doing the VoidMaps

**Comment by spindrjr** [comment]
Should only max on the level of clear now.

**Comment by spindrjr** [comment]
Haven't run into this again nor heard of it so considering it gone.
