### ISSUE TITLE
Major Issue with allSaveData in Graphs.js

### ISSUE THREAD

**Issue by HyperWeapon** [zininzinin/AutoTrimps#88]
My game stopped saving earlier today, and the script began to stop responding. It got upto the end of a run and was stopped. It should have used a portal, but it was sitting on my Map Room screen doing nothing.

After some poking around I figured out that the function allSaveData in Graphs.js stores some data in localStorage for the script to pull from.
When I looked up what was stored in my localStorage, allSaveData had taken up 99% of trimps.github.io's storage quota, and allSaveData had 7120 arrays of data accumulated from over my last 50 portals or so.
After deleting allSaveData from my localStorage my game and script began to function normally again.

You might want to add some limitations before this happens to someone else.

**Comment by spindrjr** [comment]
In the version I just pushed, graph data is limited to the previous 10 portals and will automatically delete older data. Hopefully this will keep it from filling up. 

Thanks for the report, I know next to nothing about this localStorage stuff.
