### ISSUE TITLE
Script stops functioning on auto portal + other wonkiness

### ISSUE THREAD

**Issue by coderpatsy** [zininzinin/AutoTrimps#89]
Console.error:
main.js?65:661 Uncaught TypeError: Cannot read property 'className' of null

I think it's because I set no challenge and that broke the selectChallenge function there.

Also while I'm here and too lazy to log another issue (<_<), auto-built wormholes caused it to trigger the auto portal with helium/hr set during a no challenge run (going for speedrun achievements on the prison). Getting 80 helium when I have nearly 2 million is obviously not ideal.

A few ideas off the top of my head that might help?
- A settable minimum zone before auto portal
- Not auto portaling until you make more helium than spent on wormholes
- Checking percentage of helium that would be earned vs helium total

**Comment by spindrjr** [comment]
Thanks I'll fix that crash error on my next push.

Re: the wormholes he/hr autoportal interaction: I'm not sure I really want to go coding special cases for this when it can be reasonably circumvented by turning autoPortal off or using the custom zone setting. So I will close this issue once I fix the error, but I will keep in mind this interaction in case I come up with an elegant way to fix it.

Thanks for the reports.

**Comment by spindrjr** [comment]
Crash should be fixed.
