### ISSUE TITLE
[QoL] Trigger Fight Button in World 1

### ISSUE THREAD

**Issue by weltvagabund** [zininzinin/AutoTrimps#9]
If you have Carpentry on a high level and you hit the first Territory fighting will stop as soon as your current Trimp dies until the Trimp Bar is refilled. This takes with the Script some time 30+ Seconds. Playing by hand i just press the Fight Button manually.
The Script should activate the Fight Button if it detects that there are no fights at least 3 free Trimps and it is in World 1 to smoothen the start.

**Comment by WG-SpaceCoder** [comment]
I believe spin is working on cleaning up the early game automation, but I'll look into this.  
Would it be better to wait till you are at 80% instead of totally full?

**Comment by weltvagabund** [comment]
This is slightly different. This is always the issue. I always wait 30+ Seconds on World 1 that the Trimps fill up. This Time varies slightly depending on the Job Hire algorithm. Before the Change from Spin World 1 took 8+ Minutes. Now its about 4 Minutes. If I press fight about 3 to 4 times while in World 1, it takes about 1 Minute to complete.

**Comment by spindrjr** [comment]
Manual gather function will now manually fight as long as you are zone 4 or below and have at least ~12% of population breeding.

**Comment by weltvagabund** [comment]
This is not working..... I think it never made it to V2. I miss this feature. Can we reopen this?

**Comment by spindrjr** [comment]
It's on my personal list.

**Comment by spindrjr** [comment]
This should be fixed in latest version.
