### ISSUE TITLE
[Optimisation] Void Map Optimisation / Toxcity Runs

### ISSUE THREAD

**Issue by weltvagabund** [zininzinin/AutoTrimps#92]
Hey, I noticed, that the Script only starts the Voidmaps, when it has 1500 Tox Markers. To optimize this, it should start with over 1400 markers, because it could get the last 100 Markers in the Voidmap itself. Probably this limit is even lower due to the 250% difficulty these Maps have. This could save some Seconds on a Run.

**Comment by spindrjr** [comment]
I've been working on void map stuff a lot recently, so maybe you had a version acting up, or maybe you are seeing something acting up, but it actually does start doing them at 1400 stacks.

**Comment by weltvagabund** [comment]
I confess, the instance of the script i ran, when i saw the behavior was about 36 hrs old. You are just too quick then :) :+1:  BTW. Thanks for putting all the effort in this.

**Comment by spindrjr** [comment]
Cool. Good lookin out.
