### ISSUE TITLE
enoughDamage undefined

### ISSUE THREAD

**Issue by Thiana** [zininzinin/AutoTrimps#93]
The latest push is giving me an error 'NewUI.js:345 Uncaught ReferenceError: enoughDamage is not defined' right after loading. I have tried clearing the cache before reloading. 

Thanks.

Edit: I'm using Chrome on Win8.1

**Comment by Suslikuraip** [comment]
In my case no error is shown. Using Chrome on Win 7 Professional 64bit

**Comment by Thiana** [comment]
If you hit F12 in the Chrome tab with Trimps, do you see the error listed at the bottom of the console on the right?

**Comment by Suslikuraip** [comment]
17:09:19 initializeAutoTrimps
Graphs.js:303 Got allSaveData. Yay!
NewUI.js:345 Uncaught ReferenceError: enoughDamage is not
definedupdateCustomButtons @ NewUI.js:345settingChanged @
NewUI.js:240onclick @ VM1737:1
NewUI.js:345 Uncaught ReferenceError: enoughDamage is not
definedupdateCustomButtons @ NewUI.js:345mainLoop @ AutoTrimps2.js:1584

2016-02-25 16:56 GMT+02:00 Thiana notifications@github.com:

**Comment by spindrjr** [comment]
Should be fixed. Sorry for trouble.
