### ISSUE TITLE
Latest upgrade hungs up

### ISSUE THREAD

**Issue by Suslikuraip** [zininzinin/AutoTrimps#94]
Withs chrome latest upgrade dont work. After refresh buys upgrades, assigns workers but hungs up withs automaps. Also creates map but does not start "Better Auto Fight"

**Comment by Suslikuraip** [comment]
Played withs buttons and if u turn off auto maps off fast after restart script continues to run.
All setings are default.

**Comment by Thiana** [comment]
Almost certainly the same bug as zininzinin/AutoTrimps#93

**Comment by spindrjr** [comment]
Should be fixed. Sorry for trouble.
