### ISSUE TITLE
Since the latest update Uncaught Reference Error

### ISSUE THREAD

**Issue by MasterAries7** [zininzinin/AutoTrimps#95]
zininzinin.github.io/AutoTrimps/NewUI.js:339 Uncaught ReferenceError: needPrestige is not defined

also the script is still highlighting as it should, but it doesnt seem to actually be doing ANYTHING, other than that.

**Comment by MasterAries7** [comment]
Forgot to mention Chrome Version 48.0.2564.116 m, windows 7

**Comment by spindrjr** [comment]
Should be fixed. Sorry for trouble.
