### ISSUE TITLE
Reloaded page, Everything is off, but its still running

### ISSUE THREAD

**Issue by MasterAries7** [zininzinin/AutoTrimps#97]
I reloaded the page, and according to the Automation options everything is turned off, but it was still building buildings, assigning jobs and running maps.

here is a screenshot

http://i.imgur.com/fqWqVLx.png

**Comment by MasterAries7** [comment]
First thing i recieve when i load the page is

Huh, autoTrimpSettings was undefined in the UI script...

If that helps

**Comment by spindrjr** [comment]
Is this still happening to you if you refresh/reload the script right now? There was a bug earlier but that would probably crash it outright. I load my export into a private mode browser (which resets the local settings) and it properly doesnt' run with everything off.

I have to go for now but I can look into this further when I get back.

**Comment by MasterAries7** [comment]
I deleted the script from Tampermonkey, then reinstalled it, and it works fine now.
